networks:
  hasher:
    internal: true
  redis:
    internal: true
  rng:
    internal: true
services:
  hasher:
    command: hasher.rb
    entrypoint: ruby
    image: escallada/dockercoins:2021-09-hasher
    networks:
      - hasher
    volumes:
      - ./hasher/hasher.rb:/app/hasher.rb:ro
    working_dir: /app/
  redis:
    command: redis-server
    entrypoint: docker-entrypoint.sh
    image: library/redis:alpine
    networks:
      - redis
    volumes:
      - redis:/data/:rw
    working_dir: /data/
  rng:
    command: rng.py
    entrypoint: python
    image: escallada/dockercoins:2021-09-rng
    networks:
      - rng
    volumes:
      - ./rng/rng.py:/app/rng.py:ro
    working_dir: /app/
  webui:
    command: webui.js
    entrypoint: node
    image: escallada/dockercoins:2021-09-webui
    networks:
      - redis
    ports:
      - 8080:8080
    volumes:
      - ./webui/webui.js:/app/webui.js:ro
      - ./webui/files/:/app/files/:ro
    working_dir: /app/
  worker:
    command: worker.py
    entrypoint: python
    image: escallada/dockercoins:2021-09-worker
    networks:
      - hasher
      - redis
      - rng
    volumes:
      - ./worker/worker.py:/app/worker.py:ro
    working_dir: /app/
version: '3.8'
volumes:
  redis:
