name: CI-swarm
env:
  github_username: escallada
  github_repo: dockercoins
  github_branch: 2021-09
on:
  push:
    branches:
      - 2021-09
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          mkdir build-context/
          for app in hasher rng webui worker
          do
            docker image build --file Dockerfile-${app} --tag ${github_username}/${github_repo}:${github_branch}-${app} build-context/
          done
      - name: swarm
        run: docker swarm init
      - name: deploy
        run: docker stack deploy --compose-file docker-compose.yaml ${github_repo}
      - name: test
        run: |
          while true
          do
            sleep 10
            curl -s localhost:8080/index.html | grep 'DockerCoin Miner WebUI' && break
          done
